feat: (RI-4198) Add onepassword provider
gbh-tech/dot-env-generator pull request #1
Opened 2024-09-03 15:35 UTC by javiercm1410

2024-09-03 17:52 UTC, b-nicasio commented on .github/workflows/lint.yml
> +  pull_request:
On pull request only to main, remember this is part of the TBD rules

2024-09-03 17:52 UTC, b-nicasio commented on .github/workflows/lint.yml
> +      - name: 🔎 Validate PR title with commitlint
Missed an space here between steps

2024-09-03 17:53 UTC, b-nicasio commented on .husky/pre-commit
> +fi
Why don't we add the code lint here as well?

2024-09-03 17:55 UTC, javiercm1410 commented on .github/workflows/lint.yml
> +  pull_request:
done

2024-09-03 17:57 UTC, javiercm1410 commented on .husky/pre-commit
> +fi
nice

2024-09-03 18:05 UTC, angelmadames requested changes
I'm confused as to why we removed the upload to S3? 👀 
Even if we are using releases , we can have an alternative backup/download mechanism.

2024-09-03 18:35 UTC, javiercm1410 commented on src/parser.ts
> +  fs.appendFileSync(filePath, envContent + '\n', 'utf8');
the new value will override the previous one on code, but both will be on the file

2024-09-04 14:24 UTC, javiercm1410 commented on src/parser.ts
> +  fs.appendFileSync(filePath, envContent + '\n', 'utf8');
This logic was added!

2024-09-04 14:24 UTC, javiercm1410 commented on src/commands/op.ts
> +          (obj, item) => Object.assign(obj, { [item.title]: item.value }), {});
Nice, done!

2024-09-04 19:43 UTC, angelmadames approved these changes

2024-09-04 19:54 UTC, merged